name: nakama1
data_dir: "./data/"

socket:
  server_key: "defaultkey"
  port: 7350
  address: "0.0.0.0"  # Listen on all interfaces
  max_message_size_bytes: 4096
  read_buffer_size_bytes: 4096
  write_buffer_size_bytes: 4096
  ping_period_ms: 15000
  pong_wait_ms: 25000
  write_wait_ms: 5000
  outgoing_queue_size: 16

server:
  port: 7350  # Use same port for HTTP and WebSocket
  address: "0.0.0.0"
  cors:
    allowed_origins: ["*"]
    allowed_headers: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]

runtime:
  js_entrypoint: ""

logger:
  level: "info"
  format: "json"

console:
  port: 7351
  username: "admin"
  password: "password"
  address: "0.0.0.0"

session:
  token_expiry_sec: 7200

match:
  input_queue_size: 128
  call_queue_size: 128

database:
  address: []  # Set via environment variable